### ISSUE TITLE
Declination grid binning fails for countpairs_rp_pi_mocks.

### ISSUE THREAD

**Issue by j-dr** [manodeep/Corrfunc#70] opened 2016-08-23 19:31 UTC
When calling countpairs_rp_pi_mocks with lower redshift bin edges close to 0.1 or below, Corrfunc returns the error:

Error in file: ../../utils/gridlink_mocks.c     func: gridlink3D        line: 593 with expression `idec >=0 && idec < ngrid_dec[iz]'

Declination index for particle position = -1 must be within [0, 0) for cz-bin = 0

even when called on catalogs with >1 galaxy, and whose declination range is non-zero.

**Comment by manodeep** [comment] 2016-08-23 22:10
Thanks for sending me the files. I can't seem to reproduce the bug either with the `develop` or the `master` branch. Which version of `Corrfunc` are you using?

**Comment by manodeep** [comment] 2016-08-23 22:17
Here is the command I used: `./DDrppi_mocks corrfunc_example.txt a corrfunc_example.txt a rp_bins.txt 80.0 1 1 > xx`
[corrfunc_example.txt](https://github.com/manodeep/Corrfunc/files/433658/corrfunc_example.txt)
[rp_bins.txt](https://github.com/manodeep/Corrfunc/files/433659/rp_bins.txt)

Here's the output:

Running `./DDrppi_mocks' with the parameters 

                 -------------------------------------
                 file1      = corrfunc_example.txt 
                 format1    = a 
                 file2      = corrfunc_example.txt 
                 format2    = a 
                 binfile    = rp_bins.txt 
                 pimax      = 80.0 
                 cosmology flag = 1 
                 Nthreads   = 1 
                 -------------------------------------
io> WARNING: Could not parse all requested 3 fields in line 0. Skipping that line
In gridlink_mocks_index_particles_double> Running with [nmesh_x, nmesh_y, nmesh_z]  = 5,6,7.  Time taken =   0.00 sec
countpairs> gridlink seems inefficient - boosting bin refine factor - should lead to better performance
In gridlink_mocks_index_particles_double> Running with [nmesh_x, nmesh_y, nmesh_z]  = 11,13,7.  Time taken =   0.00 sec
0%.........10%.........20%.........30%.........40%.........50%.........60%.........70%.........80%.........90%.........100% done. Time taken =  0.181 secs
DDrppi> Done -  ND1=6975 ND2=6975. Time taken =   0.22 seconds, read-in time =   0.01 seconds

**Comment by j-dr** [comment] 2016-08-23 23:22
It appears that when I run it from the command line it works for me as well. It only fails when it is called via the python interface.

**Comment by manodeep** [comment] 2016-08-24 00:20
That is a new failure mode !! Let me check out the python interface.

`DDrppi_mocks` simply calls the `countpairs_rp_pi_mocks` API, as does the python interface after some type-checking. My hunch is that there is a data-type mismatch somehow, although `numpy` should throw a `RuntimeError` during the type-checking/conversion. 

Either way, I need to add checks in the `gridlink_*`  routines to ensure that the number of grids, after taking the `floor`, is at least 1.

**Comment by manodeep** [comment] 2016-08-24 01:01
Still can't reproduce the bug from current `master` or `develop` or from commit e019e56

I tried with `np.float` and `np.float32` for all cases. No crashes. Since I can't seem to figure out why you are getting the error, do you mind upgrading to the newer version. Hopefully, that bug will go away. 

Here's the code I used: [gist](https://gist.github.com/manodeep/43cb51159b379e182a430b6f833c1224)

**Comment by j-dr** [comment] 2016-08-24 17:21
I just realized that due to a bug in my own code, I didn't give you a catalog that actually caused this error. Please see [corrfunc_example_2.txt](https://github.com/manodeep/Corrfunc/files/435284/corrfunc_example_2.txt) for the right file. This now fails both at the command line and using python. Sorry to lead you astray yesterday.

The main difference in this catalog is that the lower redshift limit is actually ~0.01, which I believe you said should still work. I upgraded to the current version of the code on the master branch and I'm still getting the error.

**Comment by manodeep** [comment] 2016-08-24 19:21
Yup. I can reproduce the bug now - exists in current `master` but not in current `develop`.

**Comment by manodeep** [comment] 2016-08-24 19:40
I have added a fix to ensure number of cells is at least 1 and that fixes the issue, at least on my end. Will you check if this commit fixes your issue? `git pull && python setup.py install` in the source directory should be enough.

**Comment by j-dr** [comment] 2016-08-24 19:45
That did it, thanks for being so responsive!

**Comment by manodeep** [comment] 2016-08-24 19:49
Awesome! And not a problem at all. 

Do you mind if I keep this issue open as a reminder that the develop branch also needs to have this bug fixed ?

**Comment by j-dr** [comment] 2016-08-24 20:33
Not at all, go for it.

**Comment by manodeep** [comment] 2016-08-30 06:14
Possible similar issue has now been fixed in the `develop` branch for the upcoming `v2.0` release.

**Closed by manodeep** 2016-08-30 06:14 UTC
Labels: bug
