### ISSUE TITLE
Cant install on SDSS Jupyter notebook

### ISSUE THREAD

**Issue by tevslin** [manodeep/Corrfunc#113] opened 2017-03-26 01:35 UTC
1. got message in make and make install that modules couldn't be found when installing clone:

/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc

actually these aren't modules at all. they are gcc options.

2. tried simple pip install. got subset of messages.

   /usr/bin/ld: cannot find -lm
    /usr/bin/ld: cannot find -lpthread
    /usr/bin/ld: cannot find -lc

3. tried installing manodeep version of gcc from github:

/home/idies/anaconda3/bin/.gcc-post-link.sh: line 10: lsb_release: command not found
Couldn't locate crtXXX.o in default library search paths. You may not have it  at all. It is usually packaged in libc6-dev/glibc-devel packages. We will try  to locate crtXXX.o with system installed gcc...
There is no /usr/bin/gcc
*** Can't install the gcc package unless your system has crtXXX.o. ***

4. tried installing anaconda version. same thing.

Don't have all the details of the system Jupyter is actually running on since it is provided by SkyServer. Pretty sure it's UNIX. Usually works nicely with imported packages.

Thank you/

**Comment by manodeep** [comment] 2017-03-26 21:56
The conda error message makes me think that installing Corrfunc is not possible. Generally speaking, those errors occur because default libraries required by the compiler are not found. In any `*nix`, `libm.so`, `libpthread.so` and `libc.so` should be in the linker path. 

My guess is that SkyServer is in a sandboxed environment, specifically designed to prevent most compile/installs.

@lgarrison - do you have any idea how to reproduce/fix this?

**Comment by lgarrison** [comment] 2017-03-27 00:30
I made an account on http://compute.sciserver.org to test this, and I was able to reproduce the problem.  I managed to get much further by choosing the `Image` `Python + Dev (astro)` when creating a container, which comes with gcc and GNU Make, unlike the default image.  `git clone` followed by `python setup.py build` works without a hitch; however `python setup.py install` results in a permissions error for writing to `easy-install.pth`.  The workaround is to use a [conda env](https://conda.io/docs/using/envs.html).  So, the full solution looks like this:

- Create container with `Image` `Python + Dev (astro)`
- Open a terminal in the container, then
```
cd ~
conda create --name myenv python gsl numpy
source activate myenv
git clone https://github.com/manodeep/Corrfunc.git
cd Corrfunc
python setup.py install
```
and that should do it!  Test it with
```
conda install nose
nosetests Corrfunc
```

Trying to install Corrfunc 1.1 via `pip install Corrfunc` has its own problems, but I don't think it's worth fixing since Corrfunc 2.0 is so close to release.

**Comment by tevslin** [comment] 2017-03-27 00:44
Thank you both very much.

 

Will try this tomorrow. It sounds like a solution.

**Comment by manodeep** [comment] 2017-03-27 00:56
Thanks @lgarrison. 

If this is simply a `easy-install.pth` issue, then `python setup.py install --user` might also solve the install issue.

**Comment by lgarrison** [comment] 2017-03-27 00:59
You're probably right!  Don't know why I didn't think to try that.  I think
I was thrown off by the fact that the anaconda install was already in the
user's home directory, despite the user not having write permissions there.

**Comment by manodeep** [comment] 2017-03-27 03:33
Fingers crossed - something should work :) 

@tevslin - please let us know if you get `Corrfunc` to work.

**Comment by tevslin** [comment] 2017-03-27 12:13
Will try again tonight or tomorrow am. Thank you both for the very timely support.

**Comment by tevslin** [comment] 2017-03-28 23:19
Thanks to both of you it’s installed and tested.

 

Did it within the Jupyter notebook so I can send to you. It’s attached.

 

I very much appreciate your help and am ,looking forward to working with Corrfunc (and seeing what’s in 2.0)

**Comment by manodeep** [comment] 2017-03-28 23:22
Fantastic :). Closing this issue then.

**Closed by manodeep** 2017-03-28 23:22 UTC
Labels: Installation

**Comment by tevslin** [comment] 2017-03-28 23:44
I should’ve mention that I didn’t make the env, just added –user to the python command as you suggested.
